; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F412RE]
platform = ststm32
board = genericSTM32F412RE
framework = arduino
upload_protocol = stlink
build_flags = 
	-D HSE_VALUE=25000000UL
	-D F_CPU=96000000UL
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC   ; enables USB CDC as Serial
    -D USBCON
    -D USBD_USE_CDC
    -D HAL_PCD_MODULE_ENABLED
	-Wl,-u,_scanf_float
    -Wl,-u,_printf_float
lib_deps = askuric/Simple FOC@^2.4.0
lib_archive = false
