from __future__ import annotations

import sys
import time
import math
from collections import deque
from dataclasses import dataclass
from typing import Optional

from PyQt6 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

# Autogenerated UI
from driveDebugUI import Ui_MSAT

# Serial
try:
    import serial  # type: ignore
    from serial.tools import list_ports  # type: ignore
except Exception as e:  # pragma: no cover
    serial = None
    list_ports = None
    _SERIAL_IMPORT_ERROR = e
else:
    _SERIAL_IMPORT_ERROR = None


@dataclass
class SerialConfig:
    baud: int = 115200
    timeout_s: float = 0.0  # non-blocking reads


class PosTelemetryWindow(QtWidgets.QMainWindow):
    closed = QtCore.pyqtSignal()

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Live Positional Telemetry")
        self.resize(900, 500)

        self.plot_widget = pg.PlotWidget(title="Top / Bottom Position")
        self.setCentralWidget(self.plot_widget)

        self.plot_widget.setLabel("left", "Position")
        self.plot_widget.setLabel("bottom", "Time", units="s")
        self.plot_widget.showGrid(x=True, y=True)
        self.plot_widget.addLegend()

        self.top_curve = self.plot_widget.plot(name="Top Pos", pen="y")
        self.bottom_curve = self.plot_widget.plot(name="Bottom Pos", pen="c")

    def update_plot(self, x, top, bottom) -> None:
        self.top_curve.setData(x, top)
        self.bottom_curve.setData(x, bottom)

    def closeEvent(self, event: QtGui.QCloseEvent) -> None:
        self.closed.emit()
        super().closeEvent(event)

class PowerTelemetryWindow(QtWidgets.QMainWindow):
    closed = QtCore.pyqtSignal()

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Live Power Telemetry")
        self.resize(900, 500)

        self.plot_widget = pg.PlotWidget(title="System Current / Power")
        self.setCentralWidget(self.plot_widget)

        self.plot_widget.setLabel("left", "Value")
        self.plot_widget.setLabel("bottom", "Time", units="s")
        self.plot_widget.showGrid(x=True, y=True)
        self.plot_widget.addLegend()

        # Curves
        self.current_curve = self.plot_widget.plot(name="System Current (A)", pen="r")
        self.power_curve = self.plot_widget.plot(name="System Voltage (V)", pen="b")
        self.curr_3V = self.plot_widget.plot(name="3.3V Current (A)", pen="g")
        self.curr_5V = self.plot_widget.plot(name="5V Current (A)", pen="y")
        self.curr_12V = self.plot_widget.plot(name="12V Current (A)", pen="m")

        # Data buffers
        self.time_data = []
        self.current_data = []
        self.power_data = []
        self.curr_3V_data = []
        self.curr_5V_data = []
        self.curr_12V_data = [] 

        self.start_time = time.time()

        #limit number of points (prevents lag)
        self.max_points = 500

    def update_plot(self, current: float, power: float, curr_3V: float, curr_5V: float, curr_12V: float) -> None:
        t = time.time() - self.start_time

        self.time_data.append(t)
        self.current_data.append(current)
        self.power_data.append(power)
        self.curr_3V_data.append(curr_3V)
        self.curr_5V_data.append(curr_5V)
        self.curr_12V_data.append(curr_12V)

        # Keep buffer size under control
        if len(self.time_data) > self.max_points:
            self.time_data = self.time_data[-self.max_points:]
            self.current_data = self.current_data[-self.max_points:]
            self.power_data = self.power_data[-self.max_points:]
            self.curr_3V_data = self.curr_3V_data[-self.max_points:]
            self.curr_5V_data = self.curr_5V_data[-self.max_points:]
            self.curr_12V_data = self.curr_12V_data[-self.max_points:]

        # Update curves
        self.current_curve.setData(self.time_data, self.current_data)
        self.power_curve.setData(self.time_data, self.power_data)
        self.curr_3V.setData(self.time_data, self.curr_3V_data)
        self.curr_5V.setData(self.time_data, self.curr_5V_data)
        self.curr_12V.setData(self.time_data, self.curr_12V_data)


    def closeEvent(self, event: QtGui.QCloseEvent) -> None:
        self.closed.emit()
        super().closeEvent(event)


class DriveDebugApp(QtWidgets.QWidget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.ui = Ui_MSAT()
        self.ui.setupUi(self)

        self._ports_model = QtCore.QStringListModel(self)
        self.ui.comList.setModel(self._ports_model)

        self._ser: Optional["serial.Serial"] = None
        self._ser_cfg = SerialConfig()

        # Serial receive buffering so we can parse complete lines
        self._rx_buffer = ""

        # Telemetry window and data buffers
        self._telem_window: Optional[PosTelemetryWindow] = None
        self._telem_t = deque(maxlen=3000)
        self._telem_top = deque(maxlen=3000)
        self._telem_bottom = deque(maxlen=3000)
        self._power_window: Optional[PowerTelemetryWindow] = None
        self._power_current = 0.0
        self._power_power = 0.0
        self._power_current3v = 0.0
        self._power_current5v = 0.0
        self._power_current12v = 0.0
        self._closing_power_window = False
        self._closing_telem_window = False

        # Slightly nicer defaults for spinboxes
        for sb in [
            self.ui.pAngle, self.ui.yAngle,
            self.ui.pProportional, self.ui.pIntegral, self.ui.pDerivative,
            self.ui.yProportional, self.ui.yIntegral, self.ui.yDerivative,
        ]:
            sb.setDecimals(4)
            sb.setRange(-1000.0, 1000.0)

        self.ui.pAngle.setRange(-6.2832, 6.2832)
        self.ui.yAngle.setRange(-6.2832, 6.2832)

        # Hook buttons
        self.ui.refreshCOM.clicked.connect(self.refresh_ports)
        self.ui.selectCOM.clicked.connect(self.connect_selected_port)
        self.ui.homeMotors.clicked.connect(self.home_motors)
        self.ui.getSettings.clicked.connect(self.get_settings)

        self.ui.pAngleSet.clicked.connect(self.send_pitch_target)
        self.ui.yAngleSet.clicked.connect(self.send_yaw_target)
        self.ui.bothAngleSet.clicked.connect(self.send_both_target)

        self.ui.pSetPID.clicked.connect(lambda: self.send_pid(axis="pitch"))
        self.ui.ySetPID.clicked.connect(lambda: self.send_pid(axis="yaw"))

        self.ui.pSetVelocity.clicked.connect(lambda: self.send_velocity(axis="pitch"))
        self.ui.ySetVelocity.clicked.connect(lambda: self.send_velocity(axis="yaw"))
        self.ui.pSetLPF.clicked.connect(lambda: self.send_LPF(axis="pitch"))
        self.ui.ySetLPF.clicked.connect(lambda: self.send_LPF(axis="yaw"))

        self.ui.motorEN.toggled.connect(self.motor_enable)

        # Separate-window telemetry handling
        self.ui.livePosTelem.toggled.connect(self.toggle_live_pos_telem)
        self.ui.livePowTelem.toggled.connect(self.toggle_live_pow_telem)

        self.ui.saveSettings.clicked.connect(lambda: self.save_settings(settingType="all"))
        self.ui.setHome.clicked.connect(lambda: self.save_settings(settingType="home"))

        self.ui.testScanMode.clicked.connect(self.full_scan_mode)
        self.ui.testYawScan.clicked.connect(self.yaw_scan_mode)

        # Poll serial for incoming text
        self._poll_timer = QtCore.QTimer(self)
        self._poll_timer.setInterval(40)  # ms
        self._poll_timer.timeout.connect(self.poll_serial)
        self._poll_timer.start()

        # Start
        self.refresh_ports()
        self.log("UI ready. Select a COM port and click 'Select COM'.")

        if _SERIAL_IMPORT_ERROR is not None:
            self.log(f"WARNING: pyserial not available: {_SERIAL_IMPORT_ERROR}")

    #
    # UI helpers
    #
    def log(self, msg: str) -> None:
        ts = time.strftime("%H:%M:%S")
        self.ui.terminalOutput.append(f"[{ts}] {msg}")

    def current_port(self) -> Optional[str]:
        idx = self.ui.comList.currentIndex()
        if not idx.isValid():
            return None
        return idx.data()

    #
    # Port list
    #
    def refresh_ports(self) -> None:
        if list_ports is None:
            self._ports_model.setStringList([])
            self.log("pyserial not installed; cannot enumerate COM ports.")
            return

        ports = []
        for p in list_ports.comports():
            # Show friendly label but keep device at the front for parsing
            # Example: "COM5 - USB-SERIAL CH340 (VID:PID=1A86:7523)"
            label = f"{p.device}"
            if p.description:
                label += f" - {p.description}"
            ports.append(label)

        ports.sort()
        self._ports_model.setStringList(ports)

        if ports:
            self.ui.comList.setCurrentIndex(self._ports_model.index(0))
            self.log(f"Found {len(ports)} port(s).")
        else:
            self.log("No serial ports found.")

    #
    # Connection management
    #
    def disconnect(self) -> None:
        if self._ser is not None:
            try:
                port = self._ser.port
            except Exception:
                port = "<unknown>"
            try:
                self._ser.close()
            except Exception:
                pass
            self._ser = None
            self.log(f"Disconnected from {port}.")

    def connect_selected_port(self) -> None:
        if serial is None:
            self.log("pyserial not installed; cannot connect.")
            return

        label = self.current_port()
        if not label:
            self.log("Select a COM port first.")
            return

        # Label starts with device name (e.g., "COM5" or "/dev/ttyACM0")
        port = label.split(" - ", 1)[0].strip()

        # If already connected to this port, disconnect
        if self._ser is not None and getattr(self._ser, "port", None) == port:
            self.disconnect()
            return

        # Otherwise connect (closing any previous)
        self.disconnect()

        try:
            self._ser = serial.Serial(
                port=port,
                baudrate=self._ser_cfg.baud,
                timeout=self._ser_cfg.timeout_s,
            )
            # Many Arduino-class boards reset on open; give it a moment
            time.sleep(1.2)
            self._rx_buffer = ""
            self.log(f"Connected to {port} @ {self._ser_cfg.baud} baud.")
            self.log("Tip: if your board prints a banner on boot, it should appear below.")
        except Exception as e:
            self._ser = None
            self.log(f"Failed to open {port}: {e}")

    #
    # Serial I/O
    #
    def write_line(self, line: str) -> None:
        if self._ser is None:
            self.log("Not connected. Select a COM port first.")
            return
        try:
            payload = (line.rstrip("\n") + "\n").encode("utf-8")
            self._ser.write(payload)
            self.log(f">>> {line}")
        except Exception as e:
            self.log(f"Write failed: {e}")
            self.disconnect()

    def try_parse_telem_line(self, line: str):
        """
        Expected tagged payloads:
            POS,<time_ms>,<top_angle>,<bottom_angle>
            PWR,<time_ms>,<system_current>,<system_power>,<3v_current>,<5v_current>,<12v_current>

        Returns:
            ("POS", time_s, top, bottom)
            ("PWR", time_s, current, power, curr_3v, curr_5v, curr_12v)
            or None
        """
        s = line.strip()
        if not s:
            return None

        parts = [p.strip() for p in s.split(",")]
        if len(parts) not in (4, 7):
            return None

        tag = parts[0]

        if tag == "POS" and len(parts) == 4:
            try:
                t_raw = float(parts[1])
                v1 = float(parts[2])
                v2 = float(parts[3])
            except ValueError:
                return None
            t_s = t_raw / 1000.0
            return ("POS", t_s, v1, v2)

        elif tag == "PWR" and len(parts) == 7:
            try:
                t_raw = float(parts[1])
                v1 = float(parts[2])
                v2 = float(parts[3])
                v3 = float(parts[4])
                v4 = float(parts[5])
                v5 = float(parts[6])
            except ValueError:
                return None
            t_s = t_raw / 1000.0
            return ("PWR", t_s, v1, v2, v3, v4, v5)

        return None

    def append_telem_sample(self, t_s: float, top: float, bottom: float) -> None:
        self._telem_t.append(t_s)
        self._telem_top.append(top)
        self._telem_bottom.append(bottom)
        self.update_telem_plot()

    def update_telem_plot(self) -> None:
        if self._telem_window is None or not self._telem_t:
            return

        x_raw = list(self._telem_t)
        t0 = x_raw[0]
        x = [v - t0 for v in x_raw]

        self._telem_window.update_plot(
            x,
            list(self._telem_top),
            list(self._telem_bottom),
        )

    def poll_serial(self) -> None:
        if self._ser is None:
            return

        try:
            n = self._ser.in_waiting
            if not n:
                return

            data = self._ser.read(n)
            if not data:
                return

            self._rx_buffer += data.decode("utf-8", errors="replace")

            # Process only complete lines
            while "\n" in self._rx_buffer:
                line, self._rx_buffer = self._rx_buffer.split("\n", 1)
                line = line.replace("\r", "").strip()

                if not line:
                    continue

                telem = self.try_parse_telem_line(line)
                if telem is not None:
                    tag = telem[0]
                    t_s = telem[1]

                    if tag == "POS":
                        _, _, top, bottom = telem
                        self.append_telem_sample(t_s, top, bottom)
                        self.log(f"POS {t_s:.3f}s top={top:.3f} bottom={bottom:.3f}")

                    elif tag == "PWR":
                        _, _, current, power, curr3v, curr5v, curr12v = telem
                        self._power_current = current
                        self._power_power = power
                        self._power_current3v = curr3v
                        self._power_current5v = curr5v
                        self._power_current12v = curr12v
                        self.update_power_plot()
                        self.log(f"PWR {t_s:.3f}s current={current:.3f}A power={power:.3f}W 3V={curr3v:.3f}A 5V={curr5v:.3f}A 12V={curr12v:.3f}A")
                else:
                    self.log(line)

        except Exception as e:
            self.log(f"Read failed: {e}")
            self.disconnect()

    #
    # Telemetry window helpers
    #
    def open_telem_window(self) -> None:
        if self._telem_window is None:
            self._telem_window = PosTelemetryWindow(self)
            self._telem_window.closed.connect(self.on_telem_window_closed)

        self._telem_window.show()
        self._telem_window.raise_()
        self._telem_window.activateWindow()
        self.update_telem_plot()

    def close_telem_window(self) -> None:
        if self._telem_window is not None:
            self._closing_telem_window = True
            self._telem_window.close()
            self._telem_window = None
            self._closing_telem_window = False

    def on_telem_window_closed(self) -> None:
        self._telem_window = None

        # If the user manually closed the telemetry window,
        # make the checkbox follow that state and turn telemetry off.
        if not self._closing_telem_window and self.ui.livePosTelem.isChecked():
            blocker = QtCore.QSignalBlocker(self.ui.livePosTelem)
            self.ui.livePosTelem.setChecked(False)
            del blocker
            self.get_pos_telem(False)
            self.log("Live positional telemetry disabled.")

    def toggle_live_pos_telem(self, checked) -> None:
        if checked:
            self._telem_t.clear()
            self._telem_top.clear()
            self._telem_bottom.clear()
            self.open_telem_window()
            self.get_pos_telem(True)
            self.log("Live positional telemetry enabled.")
        else:
            self.get_pos_telem(False)
            self.log("Live positional telemetry disabled.")

    def toggle_live_pow_telem(self, checked) -> None:
        if checked:
            # Reset values when starting
            self._power_current = 0.0
            self._power_power = 0.0
            self._power_current3v = 0.0
            self._power_current5v = 0.0
            self._power_current12v = 0.0

            # Open the power window
            self.open_power_window()

            # Tell STM32 to start sending power data
            self.get_power_telem(True)

            self.log("Live power telemetry enabled.")
        else:
            # Tell STM32 to stop sending
            self.get_power_telem(False)

            # Close the window
            self.close_power_window()

            self.log("Live power telemetry disabled.")
    
    def open_power_window(self) -> None:
        if self._power_window is None:
            self._power_window = PowerTelemetryWindow(self)
            self._power_window.closed.connect(self.on_power_window_closed)

        self._power_window.show()
        self._power_window.raise_()
        self._power_window.activateWindow()
        self.update_power_plot()

    def close_power_window(self) -> None:
        if self._power_window is not None:
            self._closing_power_window = True
            self._power_window.close()
            self._power_window = None
            self._closing_power_window = False

    def on_power_window_closed(self) -> None:
        self._power_window = None

    def update_power_plot(self) -> None:
        if self._power_window is None:
            return
        self._power_window.update_plot(self._power_current, self._power_power, self._power_current3v, self._power_current5v, self._power_current12v)

    def get_power_telem(self, checked) -> None:
        if checked:
            self.write_line("W1")
        else:
            self.write_line("W0")

    #
    # Command actions (matches 2D_gimbal_Control.ino)
    #
    def send_pitch_target(self) -> None:
        # Checked = 1 = Relative Position Movement
        checked = self.ui.pRelativeEnable.isChecked()
        angle = float(self.ui.pAngle.value())
        self.write_line(f"T{angle:.3f} {checked:.3f}")

    def send_yaw_target(self) -> None:
        # Yaw = bottom motor = 'B'
        checked = self.ui.yRelativeEnable.isChecked()
        angle = float(self.ui.yAngle.value())
        self.write_line(f"B{angle:.3f} {checked:.3f}")

    def send_both_target(self) -> None:
        self.send_pitch_target()
        self.send_yaw_target()

    def home_motors(self) -> None:
        self.write_line("H")
        # Home both to saved home.

    def send_pid(self, axis: str) -> None:
        # Send a PID command to either bottom or top motor using serial.
        if axis == "pitch":
            p = float(self.ui.pProportional.value())
            i = float(self.ui.pIntegral.value())
            d = float(self.ui.pDerivative.value())
            self.write_line(f"P{p:.3f} {i:.3f} {d:.3f}")
        else:
            p = float(self.ui.yProportional.value())
            i = float(self.ui.yIntegral.value())
            d = float(self.ui.yDerivative.value())
            self.write_line(f"Y{p:.3f} {i:.3f} {d:.3f}")

    def send_velocity(self, axis: str) -> None:
        # Send a velocity command to either bottom or top motor using serial.
        if axis == "pitch":
            motor = 1
            velocity = float(self.ui.pVelocity.value())
            self.write_line(f"V{motor:.3f} {velocity:.3f}")
        else:
            motor = 0
            velocity = float(self.ui.yVelocity.value())
            self.write_line(f"V{motor:.3f} {velocity:.3f}")

    def send_LPF(self, axis: str) -> None:
        # Send an LPF command to either bottom or top motor using serial.
        if axis == "pitch":
            motor = 1
            lowPass = float(self.ui.pLPF.value())
            self.write_line(f"L{motor:.3f} {lowPass:.3f}")
        else:
            motor = 0
            lowPass = float(self.ui.yLPF.value())
            self.write_line(f"L{motor:.3f} {lowPass:.3f}")

    def motor_enable(self, checked) -> None:
        if checked:
            self.write_line("K1")
        else:
            self.write_line("K0")

    def get_pos_telem(self, checked) -> None:
        if checked:
            self.write_line("I1")
        else:
            self.write_line("I0")

    def get_settings(self) -> None:
        self.write_line("X")

    def save_settings(self, settingType: str) -> None:
        if settingType == "home":
            self.write_line(f"S{0:.1f} {0:.1f} {1:.1f}")
        if settingType == "all":
            self.write_line(f"S{1:.1f} {1:.1f} {0:.1f}")

    # Fun programs for demonstration purposes.
    def full_scan_mode(self):
        yaw_mid = 5.5
        yaw_amp = 1.5
        pitch_mid = 0.375
        pitch_amp = 0.65
        steps = 100
        dt = 0.05  # 20 Hz

        for i in range(steps + 1):
            t = i / steps
            yaw = yaw_mid + yaw_amp * math.sin(t * 2 * math.pi)
            pitch = pitch_mid + pitch_amp * math.sin(t * 2 * math.pi)
            self.write_line(f"B{yaw:.3f} 0")
            self.write_line(f"T{pitch:.3f} 0")
            time.sleep(dt)


    def yaw_scan_mode(self):
        yaw_mid = 5.5
        yaw_amp = 1.5
        steps = 100
        dt = 0.05  # 20 Hz

        for i in range(steps + 1):
            t = i / steps
            yaw = yaw_mid + yaw_amp * math.sin(t * 2 * math.pi)
            self.write_line(f"B{yaw:.3f} 0")
            time.sleep(dt)
    #
    # Cleanup
    #
    def closeEvent(self, event: QtGui.QCloseEvent) -> None:
        # Make sure telemetry is turned off on device if it was enabled
        if self.ui.livePosTelem.isChecked():
            try:
                self.get_pos_telem(False)
            except Exception:
                pass

        self.close_telem_window()
        self.disconnect()
        super().closeEvent(event)


def main() -> int:
    app = QtWidgets.QApplication(sys.argv)
    w = DriveDebugApp()
    w.show()
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())