
from __future__ import annotations

import sys
import time
import math
from dataclasses import dataclass
from typing import Optional

from PyQt6 import QtCore, QtGui, QtWidgets

# Autogenerated UI
from driveDebugUI import Ui_MSAT

# Serial
try:
    import serial  # type: ignore
    from serial.tools import list_ports  # type: ignore
except Exception as e:  # pragma: no cover
    serial = None
    list_ports = None
    _SERIAL_IMPORT_ERROR = e
else:
    _SERIAL_IMPORT_ERROR = None


@dataclass
class SerialConfig:
    baud: int = 115200
    timeout_s: float = 0.0  # non-blocking reads


class DriveDebugApp(QtWidgets.QWidget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.ui = Ui_MSAT()
        self.ui.setupUi(self)

        self._ports_model = QtCore.QStringListModel(self)
        self.ui.comList.setModel(self._ports_model)

        self._ser: Optional["serial.Serial"] = None
        self._ser_cfg = SerialConfig()

        # Slightly nicer defaults for spinboxes
        for sb in [
            self.ui.pAngle, self.ui.yAngle,
            self.ui.pProportional, self.ui.pIntegral, self.ui.pDerivative,
            self.ui.yProportional, self.ui.yIntegral, self.ui.yDerivative,
        ]:
            sb.setDecimals(4)
            sb.setRange(-1000.0, 1000.0)

        self.ui.pAngle.setRange(-6.2832, 6.2832)
        self.ui.yAngle.setRange(-6.2832, 6.2832)

        # Hook buttons
        self.ui.refreshCOM.clicked.connect(self.refresh_ports)
        self.ui.selectCOM.clicked.connect(self.connect_selected_port)
        self.ui.homeMotors.clicked.connect(self.home_motors)
        self.ui.getSettings.clicked.connect(self.get_settings)

        self.ui.pAngleSet.clicked.connect(self.send_pitch_target)
        self.ui.yAngleSet.clicked.connect(self.send_yaw_target)
        self.ui.bothAngleSet.clicked.connect(self.send_both_target)

        self.ui.pSetPID.clicked.connect(lambda: self.send_pid(axis="pitch"))
        self.ui.ySetPID.clicked.connect(lambda: self.send_pid(axis="yaw"))

        self.ui.pSetVelocity.clicked.connect(lambda: self.send_velocity(axis="pitch"))
        self.ui.ySetVelocity.clicked.connect(lambda: self.send_velocity(axis="yaw"))
        self.ui.pSetLPF.clicked.connect(lambda: self.send_LPF(axis="pitch"))
        self.ui.ySetLPF.clicked.connect(lambda: self.send_LPF(axis="yaw"))

        self.ui.motorEN.toggled.connect(self.motor_enable)
        self.ui.saveSettings.clicked.connect(lambda: self.save_settings(settingType="all"))
        self.ui.setHome.clicked.connect(lambda: self.save_settings(settingType="home"))

        self.ui.testScanMode.clicked.connect(self.full_scan_mode)
        self.ui.testYawScan.clicked.connect(self.yaw_scan_mode)

        # Poll serial for incoming text
        self._poll_timer = QtCore.QTimer(self)
        self._poll_timer.setInterval(40)  # ms
        self._poll_timer.timeout.connect(self.poll_serial)
        self._poll_timer.start()

        # Start
        self.refresh_ports()
        self.log("UI ready. Select a COM port and click 'Select COM'.")

        if _SERIAL_IMPORT_ERROR is not None:
            self.log(f"WARNING: pyserial not available: {_SERIAL_IMPORT_ERROR}")

    #
    # UI helpers
    #
    def log(self, msg: str) -> None:
        ts = time.strftime("%H:%M:%S")
        self.ui.terminalOutput.append(f"[{ts}] {msg}")

    def current_port(self) -> Optional[str]:
        idx = self.ui.comList.currentIndex()
        if not idx.isValid():
            return None
        return idx.data()

    #
    # Port list
    #
    def refresh_ports(self) -> None:
        if list_ports is None:
            self._ports_model.setStringList([])
            self.log("pyserial not installed; cannot enumerate COM ports.")
            return

        ports = []
        for p in list_ports.comports():
            # Show friendly label but keep device at the front for parsing
            # Example: "COM5 - USB-SERIAL CH340 (VID:PID=1A86:7523)"
            label = f"{p.device}"
            if p.description:
                label += f" - {p.description}"
            ports.append(label)

        ports.sort()
        self._ports_model.setStringList(ports)

        if ports:
            self.ui.comList.setCurrentIndex(self._ports_model.index(0))
            self.log(f"Found {len(ports)} port(s).")
        else:
            self.log("No serial ports found.")

    #
    # Connection management
    #

    def disconnect(self) -> None:
        if self._ser is not None:
            try:
                port = self._ser.port
            except Exception:
                port = "<unknown>"
            try:
                self._ser.close()
            except Exception:
                pass
            self._ser = None
            self.log(f"Disconnected from {port}.")

    def connect_selected_port(self) -> None:
        if serial is None:
            self.log("pyserial not installed; cannot connect.")
            return

        label = self.current_port()
        if not label:
            self.log("Select a COM port first.")
            return

        # Label starts with device name (e.g., "COM5" or "/dev/ttyACM0")
        port = label.split(" - ", 1)[0].strip()

        # If already connected to this port, disconnect
        if self._ser is not None and getattr(self._ser, "port", None) == port:
            self.disconnect()
            return

        # Otherwise connect (closing any previous)
        self.disconnect()

        try:
            self._ser = serial.Serial(
                port=port,
                baudrate=self._ser_cfg.baud,
                timeout=self._ser_cfg.timeout_s,
            )
            # Many Arduino-class boards reset on open; give it a moment
            time.sleep(1.2)
            self.log(f"Connected to {port} @ {self._ser_cfg.baud} baud.")
            self.log("Tip: if your board prints a banner on boot, it should appear below.")
        except Exception as e:
            self._ser = None
            self.log(f"Failed to open {port}: {e}")

    #
    # Serial I/O
    #
    def write_line(self, line: str) -> None:
        if self._ser is None:
            self.log("Not connected. Select a COM port first.")
            return
        try:
            payload = (line.rstrip("\n") + "\n").encode("utf-8")
            self._ser.write(payload)
            self.log(f">>> {line}")
        except Exception as e:
            self.log(f"Write failed: {e}")
            self.disconnect()

    def poll_serial(self) -> None:
        if self._ser is None:
            return
        try:
            n = self._ser.in_waiting
            if not n:
                return
            data = self._ser.read(n)
            if not data:
                return
            text = data.decode("utf-8", errors="replace")
            # Normalize newlines and append line-by-line
            for chunk in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
                if chunk.strip():
                    self.log(chunk)
        except Exception as e:
            self.log(f"Read failed: {e}")
            self.disconnect()

    #
    # Command actions (matches 2D_gimbal_Control.ino)
    #
    def send_pitch_target(self) -> None:
        # Checked = 1 = Relative Position Movement
        checked = self.ui.pRelativeEnable.isChecked()
        angle = float(self.ui.pAngle.value())
        self.write_line(f"T{angle:.3f} {checked:.3f}")

    def send_yaw_target(self) -> None:
        # Yaw = bottom motor = 'B'
        checked = self.ui.yRelativeEnable.isChecked()
        angle = float((self.ui.yAngle.value()))
        self.write_line(f"B{angle:.3f} {checked:.3f}")

    def send_both_target(self) -> None:
        self.send_pitch_target()
        self.send_yaw_target()

    def home_motors(self) -> None:
        self.write_line("H")
        # Home both to saved home.

    def send_pid(self, axis: str) -> None:
        #Send a PID command to either bottom or top motor using serial.
        if axis == "pitch":
            p = float(self.ui.pProportional.value())
            i = float(self.ui.pIntegral.value())
            d = float(self.ui.pDerivative.value())
            self.write_line(f"P{p:.3f} {i:.3f} {d:.3f}")
        else:
            p = float(self.ui.yProportional.value())
            i = float(self.ui.yIntegral.value())
            d = float(self.ui.yDerivative.value())
            self.write_line(f"Y{p:.3f} {i:.3f} {d:.3f}")
    
    def send_velocity(self, axis: str) -> None:
        #Send a PID command to either bottom or top motor using serial.
        if axis == "pitch":
            motor = 1
            velocity = float(self.ui.pVelocity.value())
            self.write_line(f"V{motor:.3f} {velocity:.3f}")
        else:
            motor = 0
            velocity = float(self.ui.yVelocity.value())
            self.write_line(f"V{motor:.3f} {velocity:.3f}")
    
    def send_LPF(self, axis: str) -> None:
        #Send a PID command to either bottom or top motor using serial.
        if axis == "pitch":
            motor = 1
            lowPass = float(self.ui.pLPF.value())
            self.write_line(f"L{motor:.3f} {lowPass:.3f}")
        else:
            motor = 0
            lowPass = float(self.ui.yLPF.value())
            self.write_line(f"L{motor:.3f} {lowPass:.3f}")
    
    def motor_enable(self, checked) -> None:
        if checked:
            self.write_line(f"K1")
        else:
            self.write_line(f"K0")

    def get_settings(self) -> None:
        self.write_line(f"X")

    def save_settings(self, settingType: str) -> None:
        if settingType == "home":
            self.write_line(f"S{0:.1f} {0:.1f} {1:.1f}")
        if settingType == "all":
            self.write_line(f"S{1:.1f} {1:.1f} {0:.1f}")


    #Fun programs for demonstration purposes.
    def full_scan_mode(self):
        sweep_time = 5
        dt = 0.01   # 100 Hz

        # Limits
        pitch_min = 1.5
        pitch_max = 2.8
        yaw_min   = 1.5
        yaw_max   = 3.3

        # Midpoints + amplitudes
        pitch_mid = (pitch_min + pitch_max) / 2
        pitch_amp = (pitch_max - pitch_min) / 2

        yaw_mid = (yaw_min + yaw_max) / 2
        yaw_amp = (yaw_max - yaw_min) / 2

        start_time = time.time()

        # Run exactly one sinusoidal cycle
        while (time.time() - start_time) < sweep_time:
            elapsed = time.time() - start_time
            theta = 2 * math.pi * (elapsed / sweep_time)

            # Smooth sinusoidal motion
            yaw = yaw_mid + yaw_amp * math.sin(theta)
            pitch = pitch_mid + pitch_amp * math.sin(theta)

            self.write_line(f"B{yaw:.4f} 0")
            self.write_line(f"T{pitch:.4f} 0")

            time.sleep(dt)

        # Optional: finish centered
        self.write_line(f"B{yaw_mid:.4f} 0")
        self.write_line(f"T{pitch_mid:.4f} 0")
    
    def yaw_scan_mode(self):
        sweep_time = 5.0          # full cycle duration (seconds)
        dt = 0.01                 # 100 Hz update (smoother than 50 Hz)

        yaw_min = 1.5
        yaw_max = 3.3
        yaw_mid = (yaw_min + yaw_max) / 2
        yaw_amp = (yaw_max - yaw_min) / 2

        t = 0.0
        start_time = time.time()

        while (time.time() - start_time) < sweep_time:
            elapsed = time.time() - start_time
            theta = 2 * math.pi * (elapsed / sweep_time)

            # Smooth sinusoidal position
            yaw = yaw_mid + yaw_amp * math.sin(theta)

            self.write_line(f"B{yaw:.4f} 0")
            time.sleep(dt)

        
    #
    # Cleanup
    #
    def closeEvent(self, event: QtGui.QCloseEvent) -> None:
        self.disconnect()
        super().closeEvent(event)


def main() -> int:
    app = QtWidgets.QApplication(sys.argv)
    w = DriveDebugApp()
    w.show()
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())